/**
 * Bundle the MCP UI into a single self-contained HTML file.
 *
 * Uses Bun.build for JS bundling and PostCSS (with @tailwindcss/postcss) for CSS.
 * The output is a TypeScript module exporting the HTML string, imported by the MCP server
 * to serve as the ext-apps resource.
 */

import { resolve } from 'node:path';
import tailwindcss from '@tailwindcss/postcss';
import postcss from 'postcss';

const projectRoot = resolve(import.meta.dirname, '..');
const entryPoint = resolve(projectRoot, 'src/mcp/mcp-app.tsx');
const cssEntry = resolve(projectRoot, 'src/mcp/styles.css');
const outputPath = resolve(projectRoot, 'src/lib/mcp/bundled-ui.ts');

// 1. Bundle JS with Bun.build
const buildResult = await Bun.build({
  entrypoints: [entryPoint],
  bundle: true,
  minify: true,
  target: 'browser',
  format: 'esm',
  define: {
    'process.env.NODE_ENV': '"production"',
  },
});

if (!buildResult.success) {
  console.error('JS bundle failed:');
  for (const log of buildResult.logs) {
    console.error(log);
  }
  process.exit(1);
}

// Escape </script> sequences to prevent premature script tag closure when inlined
const jsBundle = (await buildResult.outputs[0].text()).replaceAll('</script', '<\\/script');
console.log(`JS bundle: ${(jsBundle.length / 1024).toFixed(1)} KB`);

// 2. Process CSS with PostCSS + Tailwind
const cssSource = await Bun.file(cssEntry).text();
const postcssResult = await postcss([tailwindcss()]).process(cssSource, {
  from: cssEntry,
});
const cssBundle = postcssResult.css;
console.log(`CSS bundle: ${(cssBundle.length / 1024).toFixed(1)} KB`);

// 3. Assemble self-contained HTML
const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Recipe Flow</title>
  <style>${cssBundle}</style>
</head>
<body>
  <div id="root"></div>
  <script type="module">${jsBundle}</script>
</body>
</html>`;

console.log(`Total HTML: ${(html.length / 1024).toFixed(1)} KB`);

// 4. Write as TypeScript module
const moduleContent = `/**
 * Bundled MCP App UI HTML.
 * Auto-generated by scripts/bundle-mcp-ui.ts — do not edit manually.
 */

export const bundledHtml = ${JSON.stringify(html)};
`;

await Bun.write(outputPath, moduleContent);
console.log(`Written to ${outputPath}`);
