/**
 * Script to bundle the MCP app HTML and export it as a module.
 * Run after Vite builds the single-file HTML.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');

const distDir = resolve(projectRoot, 'src/lib/mcp/dist');
const htmlPath = resolve(distDir, 'mcp-app.html');
const outputPath = resolve(projectRoot, 'src/lib/mcp/bundled-ui.ts');

// Ensure the dist directory exists
if (!existsSync(distDir)) {
  mkdirSync(distDir, { recursive: true });
}

try {
  // Read the bundled HTML
  const html = readFileSync(htmlPath, 'utf-8');

  // Export as a TypeScript module
  const moduleContent = `/**
 * Bundled MCP App UI HTML.
 * Auto-generated by scripts/bundle-mcp-html.ts - do not edit manually.
 */

export const bundledHtml = ${JSON.stringify(html)};
`;

  writeFileSync(outputPath, moduleContent);
  console.log(`Bundled HTML exported to ${outputPath}`);
  console.log(`HTML size: ${(html.length / 1024).toFixed(1)} KB`);
} catch (error) {
  if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
    console.error(
      `Error: ${htmlPath} not found. Run 'bun run vite build --config vite.mcp.config.ts' first.`,
    );
    process.exit(1);
  }
  throw error;
}
