/**
 * Type declaration for the generated bundled UI module.
 * This file is generated by the build process (scripts/bundle-mcp-html.ts).
 */

/** The bundled HTML content for the MCP app UI */
export const bundledHtml: string;
